"""
Generate heatmap images directly from data files using Playwright rendering.
Reads Eval results + benchmark data, builds the same HTML as the frontend,
and captures full-page PNG + PDF without Streamlit chrome.

PDF is generated by converting the PNG to ensure single-page output with exact sizing.

Usage:
    uv run python frontend/pages/generate_heatmap_images.py
"""

import json
import math
from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image

# ── Paths ──
PROJECT_ROOT = Path(__file__).parent.parent.parent
BENCHMARK_DIR = PROJECT_ROOT / "Data" / "benchmark"
OUTPUT_DIR = PROJECT_ROOT / "analyse_v2" / "figures"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ── System config ──
SYSTEM_KEYS = ["llm_only", "naive_rag_a", "rag_with_judge", "agentic_rag_v3"]
SYSTEM_LABELS = ["Qwen3.6-plus", "Modular RAG", "RAG with Judge", "Agentic RAG"]

EVAL_PATHS = {
    "llm_only": "Eval/llm_only_data/result/{ds}.json",
    "naive_rag_a": "Eval/naive_rag_data/result/{ds}_schema_a.json",
    "rag_with_judge": "Eval/rag_with_judge_data/result/{ds}.json",
    "agentic_rag_v3": "Eval/agentic_rag_v3_data/result/{ds}.json",
}

BENCHMARK_FILES = {
    "hotpotqa": "HotpotQA_500_benchmark.json",
    "2wikimultihopqa": "2WikiMultihopQA_500_benchmark.json",
    "musique": "MuSiQue_500_benchmark.json",
}

TYPE_CN = {
    "bridge": "桥接型",
    "comparison": "比较型",
    "bridge_comparison": "桥接比较型",
    "compositional": "组合型",
    "inference": "推理型",
}

# ── Grid params ──
COLS = 50
CELL = 16
GAP = 1
STEP = CELL + GAP

F1_COLORS = ["#d0d0d0", "#b8e6c8", "#73c99a", "#30a954", "#1a7a3a"]
F1_LABELS = ["0", "0.25", "0.50", "0.75", "1.0"]

TYPE_COLORS = [
    "#5b8c5a", "#e6b800", "#4a90d9", "#d9534f", "#9b59b6",
    "#1abc9c", "#f39c12", "#3498db", "#e74c3c", "#8e44ad",
]


def load_question_data(ds_key: str) -> list[dict]:
    system_data = {}
    for sk in SYSTEM_KEYS:
        rel = EVAL_PATHS[sk].format(ds=ds_key)
        path = PROJECT_ROOT / rel
        with open(path, encoding="utf-8") as f:
            raw = json.load(f)
        system_data[sk] = {r["question_index"]: r for r in raw["results"]}

    bench_path = BENCHMARK_DIR / BENCHMARK_FILES[ds_key]
    with open(bench_path, encoding="utf-8") as f:
        benchmark = json.load(f)

    def get_type(item):
        if ds_key == "musique":
            hop = len(item.get("question_decomposition", []))
            return f"{hop}-hop"
        return item.get("type", "unknown")

    questions = []
    n = len(system_data[SYSTEM_KEYS[0]])
    for idx in range(n):
        f1_vec = {}
        for sk in SYSTEM_KEYS:
            r = system_data[sk].get(idx, {})
            f1_vec[sk] = float(r.get("f1", 0) or 0)
        b_item = benchmark[idx] if idx < len(benchmark) else {}
        q_type = get_type(b_item) if b_item else "unknown"
        questions.append({"idx": idx, "type": q_type, "f1_vector": f1_vec})

    return questions


def sort_questions(questions: list[dict]) -> list[dict]:
    """按题型分组，组内保持原始 benchmark 索引顺序。"""
    return sorted(questions, key=lambda q: (q["type"], q["idx"]))


def f1_class(f1: float) -> str:
    if f1 <= 0.0:
        return "c0"
    elif f1 <= 0.25:
        return "c1"
    elif f1 <= 0.50:
        return "c2"
    elif f1 <= 0.75:
        return "c3"
    else:
        return "c4"


def display_name(raw_type: str, ds_key: str) -> str:
    if ds_key == "musique":
        return raw_type
    return TYPE_CN.get(raw_type, raw_type)


def group_by_type(sorted_qs: list[dict]) -> list[tuple[str, list[dict]]]:
    groups = []
    cur_type = None
    cur_list = []
    for q in sorted_qs:
        if q["type"] != cur_type:
            if cur_type is not None:
                groups.append((cur_type, cur_list))
            cur_type = q["type"]
            cur_list = [q]
        else:
            cur_list.append(q)
    if cur_list:
        groups.append((cur_type, cur_list))
    return groups


def build_heatmap_html(sorted_qs: list[dict], ds_key: str, ds_label: str) -> str:
    n = len(sorted_qs)
    type_groups = group_by_type(sorted_qs)
    type_ranges = [(tname, len(qs)) for tname, qs in type_groups]

    max_grid_w = COLS * CELL + (COLS - 1) * GAP
    SYS_GAP = 5

    html_parts = []

    html_parts.append(f"""<div id="hm-root" style="font-family: 'SF Mono', 'Consolas', monospace; background: white; padding: 24px 32px; width: 100%; overflow-x: auto;">
<style>
.hm-inner {{ width: fit-content; min-width: 1020px; }}
.hm-cell {{ position: absolute; width: {CELL}px; height: {CELL}px; border-radius: 3px; }}
.c0 {{ background: #d0d0d0; }}
.c1 {{ background: #b8e6c8; }}
.c2 {{ background: #73c99a; }}
.c3 {{ background: #30a954; }}
.c4 {{ background: #1a7a3a; }}
.hm-sys-row {{ display: flex; align-items: center; margin-bottom: {SYS_GAP}px; }}
.hm-label {{ width: 140px; font-weight: 700; font-size: 13px; text-align: right; padding-right: 12px; flex-shrink: 0; white-space: nowrap; color: #222; }}
.hm-grid {{ position: relative; }}
.hm-border {{ position: absolute; inset: -0.5px; border: 1px solid #ccc; pointer-events: none; border-radius: 3px; }}
.hm-type-header {{ font-size: 14px; font-weight: 700; color: #222; margin: 18px 0 10px; font-family: 'SF Mono', 'Consolas', monospace; display: flex; align-items: center; gap: 8px; }}
.hm-type-line {{ flex: 1; height: 1px; background: #ddd; }}
.hm-type-divider {{ border-top: 1px dashed #ccc; margin: 4px 0; }}
.hm-title {{ font-size: 16px; font-weight: 700; color: #222; margin-bottom: 16px; font-family: 'SF Mono', 'Consolas', monospace; }}
.hm-legend {{ margin-top: 24px; }}
.hm-dist-title {{ font-size: 12px; font-weight: 700; margin-bottom: 6px; font-family: 'SF Mono', 'Consolas', monospace; }}
.hm-dist {{ width: {max_grid_w}px; height: 14px; border-radius: 2px; overflow: hidden; display: flex; }}
.hm-dist-seg {{ height: 100%; }}
.hm-f1-title {{ font-size: 12px; font-weight: 700; margin-top: 12px; margin-bottom: 6px; font-family: 'SF Mono', 'Consolas', monospace; }}
.hm-f1-row {{ display: flex; align-items: center; gap: 10px; }}
.hm-f1-block {{ width: 14px; height: 14px; border-radius: 3px; border: 1px solid #888; flex-shrink: 0; }}
.hm-f1-label {{ font-size: 11px; color: #555; font-family: 'SF Mono', 'Consolas', monospace; }}
.hm-f1-arrow {{ font-size: 11px; color: #888; margin-left: 8px; font-family: 'SF Mono', 'Consolas', monospace; }}
.hm-type-row {{ display: flex; flex-wrap: wrap; gap: 14px; margin-top: 10px; }}
.hm-type-item {{ display: flex; align-items: center; gap: 4px; }}
.hm-type-swatch {{ width: 10px; height: 10px; border-radius: 2px; border: 1px solid #888; flex-shrink: 0; }}
.hm-type-name {{ font-size: 10px; color: #555; font-family: 'SF Mono', 'Consolas', monospace; }}
</style>
<div class="hm-inner">""")

    html_parts.append(f'<div class="hm-title">F1 Contribution Heatmap &mdash; {ds_label} (N={n})</div>')

    for gi, (tname, tqs) in enumerate(type_groups):
        tn = len(tqs)
        tdisplay = display_name(tname, ds_key)

        html_parts.append(f'<div class="hm-type-header"><span>{tdisplay}</span> <span style="color:#888;font-weight:400;font-size:12px">(N={tn})</span><span class="hm-type-line"></span></div>')

        trows = math.ceil(tn / COLS)
        tgrid_h = trows * CELL + (trows - 1) * GAP
        tcols = min(tn, COLS)
        tgrid_w = tcols * CELL + (tcols - 1) * GAP

        for s in range(4):
            label = SYSTEM_LABELS[s]
            sk = SYSTEM_KEYS[s]

            html_parts.append('<div class="hm-sys-row">')
            html_parts.append(f'<div class="hm-label">{label}</div>')
            html_parts.append(f'<div class="hm-grid" style="width:{tgrid_w}px;height:{tgrid_h}px;">')
            html_parts.append('<div class="hm-border"></div>')

            for j, q in enumerate(tqs):
                col = j % COLS
                row = j // COLS
                f1 = q["f1_vector"][sk]
                cls = f1_class(f1)
                x = col * STEP
                y = row * STEP
                html_parts.append(f'<div class="hm-cell {cls}" style="left:{x}px;top:{y}px;"></div>')

            html_parts.append('</div></div>')

        if gi < len(type_groups) - 1:
            html_parts.append('<div class="hm-type-divider"></div>')

    html_parts.append('<div class="hm-legend">')

    html_parts.append('<div class="hm-dist-title">Question Type Distribution</div>')
    html_parts.append('<div class="hm-dist">')
    for idx, (tname, tcount) in enumerate(type_ranges):
        frac = tcount / n
        tc = TYPE_COLORS[idx % len(TYPE_COLORS)]
        html_parts.append(f'<div class="hm-dist-seg" style="width:{frac*100:.4f}%;background:{tc};"></div>')
    html_parts.append('</div>')

    html_parts.append('<div class="hm-f1-title">F1 Score</div>')
    html_parts.append('<div class="hm-f1-row">')
    for k in range(5):
        html_parts.append(f'<div class="hm-f1-block c{k}"></div>')
        html_parts.append(f'<span class="hm-f1-label">{F1_LABELS[k]}</span>')
    html_parts.append('<span class="hm-f1-arrow">&rarr; increasing F1</span>')
    html_parts.append('</div>')

    html_parts.append('<div class="hm-type-row">')
    for idx, (tname, tcount) in enumerate(type_ranges):
        tc = TYPE_COLORS[idx % len(TYPE_COLORS)]
        tdisplay = display_name(tname, ds_key)
        html_parts.append(f'<div class="hm-type-item"><div class="hm-type-swatch" style="background:{tc};"></div><span class="hm-type-name">{tdisplay} ({tcount})</span></div>')
    html_parts.append('</div>')

    html_parts.append("</div></div>")
    return "".join(html_parts)


DS_KEYS = ["hotpotqa", "2wikimultihopqa", "musique"]
DS_LABELS = {"hotpotqa": "HotpotQA", "2wikimultihopqa": "2WikiMultihopQA", "musique": "MuSiQue"}


def calc_content_height(sorted_qs: list[dict]) -> int:
    """Calculate exact content height in pixels (matches HTML layout)."""
    type_groups = group_by_type(sorted_qs)
    h = 0
    # Title
    h += 16 + 16  # font-size + margin-bottom
    for i, (_, tqs) in enumerate(type_groups):
        # Type header
        h += 24
        tn = len(tqs)
        trows = math.ceil(tn / COLS)
        # 4 system rows
        for _ in range(4):
            h += trows * CELL + (trows - 1) * GAP + 5  # SYS_GAP
        # Divider (except last)
        if i < len(type_groups) - 1:
            h += 5  # margin 4 + border 1
    # Legend
    h += 24  # margin-top
    h += 12 + 6  # dist title + margin
    h += 14  # dist bar
    h += 12 + 12 + 6  # f1 title margin-top + font + margin
    h += 14  # f1 row (blocks)
    h += 10  # type row margin-bottom
    # Bottom padding
    h += 24
    return h


def calc_content_width(sorted_qs: list[dict]) -> int:
    """Calculate exact content width in pixels."""
    max_grid_w = COLS * CELL + (COLS - 1) * GAP  # 845
    label_w = 152  # 140 + 12 padding
    padding_lr = 32 * 2
    return label_w + max_grid_w + padding_lr


def main():
    # High-res rendering scale factor: 5× → 480 DPI PDF (5 × 96 DPI)
    SCALE = 5

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)

        for ds_key in DS_KEYS:
            ds_label = DS_LABELS[ds_key]
            print(f"Processing {ds_label}...")

            questions = load_question_data(ds_key)
            sorted_qs = sort_questions(questions)
            heatmap_html = build_heatmap_html(sorted_qs, ds_key, ds_label)

            content_w = calc_content_width(sorted_qs)
            content_h = calc_content_height(sorted_qs)

            # Scale the HTML content for high-res rendering
            # The transform:scale() upsizes everything; wrapper div sizes it back
            # so layout matches the original exactly, but rendered at SCALE× pixel density
            full_html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            background: white;
            width: {content_w * SCALE}px;
        }}
        .hm-root-scaler {{
            width: {content_w}px;
            transform-origin: 0 0;
            transform: scale({SCALE});
        }}
    </style>
</head>
<body>
<div class="hm-root-scaler">
{heatmap_html}
</div>
</body>
</html>"""

            png_path = OUTPUT_DIR / f"heatmap_f1_{ds_label}.png"
            pdf_path = OUTPUT_DIR / f"heatmap_f1_{ds_label}.pdf"

            # PNG: render at SCALE× resolution for sharp output
            vp_w = content_w * SCALE + 10
            vp_h = content_h * SCALE + 10
            context2 = browser.new_context(viewport={"width": vp_w, "height": vp_h})
            page2 = context2.new_page()
            page2.set_content(full_html, wait_until="networkidle")
            page2.wait_for_timeout(300)
            page2.screenshot(path=str(png_path), full_page=True)
            page2.close()
            context2.close()
            print(f"  Saved {png_path.name}  ({vp_w}x{vp_h}px viewport, {SCALE}× scale)")

            # PDF: embed high-res PNG at correct physical dimensions
            # Physical page size = content_w × content_h at 96 DPI
            # Pixel size = content_w×SCALE × content_h×SCALE
            # So effective DPI = 96 × SCALE = {96 * SCALE}
            pdf_w_in = content_w / 96.0
            pdf_h_in = content_h / 96.0
            # Pillow needs DPI = pixels / inches for correct PDF page size
            effective_dpi = int(96 * SCALE)

            img = Image.open(png_path)
            img.info['dpi'] = (effective_dpi, effective_dpi)
            img.save(pdf_path, 'PDF', resolution=effective_dpi)
            img.close()

            actual_page_w = img.width / effective_dpi
            actual_page_h = img.height / effective_dpi
            print(f"  Saved {pdf_path.name}  ({img.width}x{img.height}px @ {effective_dpi} DPI → {actual_page_w:.1f}x{actual_page_h:.1f}in, single page)")

        browser.close()
    print("All images generated successfully.")


if __name__ == "__main__":
    main()
